CREATE DATABASE PAINEIRAS_EVENTOS;

CREATE TABLE tb_usuarios(
	ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(80) NOT NULL , 
	CPF VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL , 
	DATA_NASCIMENTO VARCHAR(10) NOT NULL,
	DATA_ANIVERSARIO CHAR(5) NULL,
	SENHA VARCHAR(255) NOT NULL , 
	TIPO_USUARIO CHAR(1) NOT NULL
);

CREATE TABLE tb_funcionarios(
	ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    CARGO VARCHAR(80) NOT NULL , 
    ENDERECO VARCHAR(255) NULL,
    TURNO CHAR(1),
    FOREIGN KEY (id_usuario) REFERENCES tb_usuarios(id_usuario)
);

CREATE TABLE tb_moradores(
	ID_MORADOR INT AUTO_INCREMENT PRIMARY KEY,
    BLOCO INT NOT NULL,
    APARTAMENTO INT NOT NULL,
    TIPO_RESIDENTE  CHAR(1),
    FOREIGN KEY (id_usuario) REFERENCES tb_usuarios(id_usuario)
);